"""add_item_splits_and_guest_count

Revision ID: d8c39bd25055
Revises: 34af9e3f9315
Create Date: 2025-10-26 21:50:27.333748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c39bd25055'
down_revision: Union[str, Sequence[str], None] = '34af9e3f9315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('item_splits', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('number_of_guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'number_of_guests')
    op.drop_column('sessions', 'item_splits')
    # ### end Alembic commands ###
